In [2]:
import pandas as pd
import numpy as np
import os
os.chdir(r'C:/my_code/learning-notes/2.数据分析')   # 修改相对路径的位置.
# os.getcwd()

# 解决中文显示问题，下面的代码只需运行一次即可
import matplotlib as plt
plt.rcParams['font.sans-serif'] = ['SimHei']    # 如果是Mac本, 不支持SimHei的时候, 可以修改为 'Microsoft YaHei' 或者 'Arial Unicode MS'
plt.rcParams['axes.unicode_minus'] = False

from sqlalchemy import create_engine    # 导入引擎对象

# 1. Pandas操作csv文件

In [3]:
# 1.机器学习概述. 读取csv文件, 获取数据.
# 参数解释: 参1: 文件路径, 参2: 分隔符, 参3: 读取的列名.
df = pd.read_csv('./data/stock_day.csv', sep=',', usecols=['open', 'high', 'close', 'low'])
df

             open   high  close    low
2018-02-27  23.53  25.88  24.16  23.53
2018-02-26  22.80  23.78  23.53  22.80
2018-02-23  22.88  23.37  22.82  22.71
2018-02-22  22.25  22.76  22.28  22.02
2018-02-14  21.49  21.99  21.92  21.48
...           ...    ...    ...    ...
2015-03-06  13.17  14.48  14.28  13.13
2015-03-05  12.88  13.45  13.16  12.87
2015-03-04  12.80  12.92  12.90  12.61
2015-03-03  12.52  13.06  12.70  12.52
2015-03-02  12.25  12.67  12.52  12.20

[643 rows x 4 columns]

In [4]:
# 2. 把读取到的数据, 写到文件中.
df[:10].to_csv('./data/my_file1.csv', sep=',', index=False)
print('写入成功!')

写入成功!

In [5]:
# 3. 特殊的csv文件 -> tsv文件. 
# 区别: csv文件 -> 以,做分割,    tsv文件 -> 是以tab键分隔的.
df[:5].to_csv('./data/my_file2.tsv', sep='\t', index=True)
print('写入成功!')

写入成功!

In [6]:
# 4. 读取tsv文件.
# 参1: 文件路径, 参2: 分隔符, 参3: 把索引为0的列(第1列) 设置为索引.
df2 = pd.read_csv('./data/my_file2.tsv', sep='\t', index_col=0)
df2

             open   high  close    low
2018-02-27  23.53  25.88  24.16  23.53
2018-02-26  22.80  23.78  23.53  22.80
2018-02-23  22.88  23.37  22.82  22.71
2018-02-22  22.25  22.76  22.28  22.02
2018-02-14  21.49  21.99  21.92  21.48

# 2.Pandas操作MySQL数据表

In [ ]:
# 前提: 你的Anaconda要先装: pymysql 和 sqlalchemy 模块.
# 安装方式: pip install 模块名

# 此外, 你的电脑还需要安装: mysql数据库

In [7]:
# 需求: 把数据写入到MySQL数据表.
# 1.机器学习概述. 准备写到MySQL数据表的 数据.
data = pd.read_csv('./data/csv示例文件.csv', encoding='gbk', index_col=0)
data

     birthday name   AKA
0    1960/5/7  刘海柱  职业法师
1    1978/9/1  赵金龙   大力哥
2  1984/12/27  周立齐  窃格瓦拉
3   1969/1/24   于谦  相声皇后

In [ ]:
# 2. 导包
# from sqlalchemy import create_engine    # 导入引擎对象, 我们写到第1个单元格了.

In [9]:
# 3. 创建引擎对象.
#                       数据库+模块名://数据库的用户名:密码@主机名:端口号/要操作的数据库名?编码方式'
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/day01?charset=utf8')

# 4. 具体的往数据库写数据的动作.
# 参1: 数据表名, 参2: 引擎对象, 参3: 是否把索引写入数据库, 
# 参4: 如果数据表存在, 则如何处理(append->追加数据; replace->覆盖数据)
data.to_sql('my_table', engine, index=False, if_exists='append')
# 5. 提示
print('写入成功!')

写入成功!

In [10]:
# 6. 从SQL表中读取数据.
# 参1: 数据表名, 参2: 引擎对象.
sql_df = pd.read_sql('my_table', engine)    # 读取全表.
sql_df = pd.read_sql('select name, AKA from my_table limit 0,2', engine)    # 读取表中指定数据..
sql_df

  name   AKA
0  刘海柱  职业法师
1  赵金龙   大力哥

# 3.Pandas读写json文件

In [11]:
# 1.机器学习概述. 读取json文件.
# 参1: 文件路径, 参2: 读取的格式, 参3: 是否按行读取.
json_df = pd.read_json('./data/test.json', orient='records', lines=True)
# 2. 打印读取到的内容.
json_df

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
3,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
4,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0

In [12]:
# 2. 把上述的数据, 写到json文件中.
# json_df.to_json('./data/my_file3.json', orient='records')   # 结果为: [{}, {}, {}...]
# json_df.to_json('./data/my_file3.json', orient='records', lines=True)   # 结果为: {} {} {}... 逐行形式

# json_df.to_json('./data/my_file3.json')     # 格式为: columns: {...}
# json_df.to_json('./data/my_file3.json', orient='index')     # 格式为: index: {...}


json_df.to_json('./data/my_file3.json', orient='records', lines=True)   # 结果为: {} {} {}... 逐行形式
print('写入成功!')

写入成功!