In [4]:
import pandas as pd
import numpy as np
import os
os.chdir(r'D:/bc/python/pandasProject')   # 修改相对路径的位置.
os.getcwd()

# 解决中文显示问题，下面的代码只需运行一次即可
import matplotlib as plt
plt.rcParams['font.sans-serif'] = ['SimHei']    # 如果是Mac本, 不支持SimHei的时候, 可以修改为 'Microsoft YaHei' 或者 'Arial Unicode MS'
plt.rcParams['axes.unicode_minus'] = False
from sqlalchemy import create_engine

In [8]:
df = pd.read_csv('./data/stock_day.csv',sep=',',usecols=['open','high','close','low'])
df

             open   high  close    low
2018-02-27  23.53  25.88  24.16  23.53
2018-02-26  22.80  23.78  23.53  22.80
2018-02-23  22.88  23.37  22.82  22.71
2018-02-22  22.25  22.76  22.28  22.02
2018-02-14  21.49  21.99  21.92  21.48
...           ...    ...    ...    ...
2015-03-06  13.17  14.48  14.28  13.13
2015-03-05  12.88  13.45  13.16  12.87
2015-03-04  12.80  12.92  12.90  12.61
2015-03-03  12.52  13.06  12.70  12.52
2015-03-02  12.25  12.67  12.52  12.20

[643 rows x 4 columns]

In [11]:
df[:10].to_csv('./data/my_file1.csv',sep=',',index=False)
print('写入成功！')

写入成功！

In [12]:
# 特殊的csv文件 -> tsv文件(TAB)
df[:5].to_csv('./data/my_file2.csv',sep='\t',index=True)
print('写入成功！')

写入成功！

In [5]:
df2 = pd.read_csv('./data/my_file2.csv',sep='\t',index_col=0)
df2

             open   high  close    low
2018-02-27  23.53  25.88  24.16  23.53
2018-02-26  22.80  23.78  23.53  22.80
2018-02-23  22.88  23.37  22.82  22.71
2018-02-22  22.25  22.76  22.28  22.02
2018-02-14  21.49  21.99  21.92  21.48

# 2.Pandas操作MySQL数据表

## 2.1  从csv文件中读写数据

In [6]:
data = pd.read_csv('./data/csv示例文件.csv',encoding='gbk',index_col=0)
data

     birthday name   AKA
0    1960/5/7  刘海柱  职业法师
1    1978/9/1  赵金龙   大力哥
2  1984/12/27  周立齐  窃格瓦拉
3   1969/1/24   于谦  相声皇后

## 2.2 pyMyQSL 读取写入文件

In [10]:
#from sqlalchemy import create_engine
#创建数据库连接
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/day01?charset=utf8') #
#           数据表名     引擎对象  是否把索引写入数据库  如果数据存在,如何处理
#写入数据库 -> my_table -> 数据表名 -> engine -> 引擎对象 -> index=False -> 是否把索引写入数据库 -> if_exists='append' -> 如果数据存在,如何处理
data.to_sql('my_table',engine,index=False,if_exists='append') #append追加 replace 覆盖
print('写入成功！')

写入成功！

In [13]:
#读取数据库 -> my_table -> 数据表名 -> engine -> 引擎对象 -> sql_df -> 读取结果
sql_df = pd.read_sql('my_table',engine)
sql_df = pd.read_sql('select name,AKA from my_table limit 0,2',engine)
sql_df

  name   AKA
0  刘海柱  职业法师
1  赵金龙   大力哥

# 3.从json文件中读写数据

In [15]:
# 创建数据框 -> json_df -> DataFrame -> orient='records' -> 数据格式 -> lines=True -> 是否换行
json_df = pd.read_json('./data/test.json',orient='records',lines=True)
json_df

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
3,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
4,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0

In [23]:
#json_df.to_json('./data/my_file3.json',orient='records') #结果为: [{"name": "张三", "age": 18}, {"name": "李四", "age": 19}]
json_df.to_json('./data/my_file3.json',orient='records',lines=True) #结果为: {} {} {}
#json_df.to_json('./data/my_file.json') #字典 套 字典
#json_df.to_json('./data/my_file.json',orient='index')

7385137788721