In [1]:
import pandas as pd
import numpy as np
import os
os.chdir(r'C:/my_code/learning-notes/2.数据分析')   # 修改相对路径的位置.
# os.getcwd()

# 解决中文显示问题，下面的代码只需运行一次即可
import matplotlib as plt
plt.rcParams['font.sans-serif'] = ['SimHei']    # 如果是Mac本, 不支持SimHei的时候, 可以修改为 'Microsoft YaHei' 或者 'Arial Unicode MS'
plt.rcParams['axes.unicode_minus'] = False

# 1. Pandas的增删改查操作 -> 增

In [2]:
# 1. 准备数据.
df = pd.read_csv('./data/1960-2019全球GDP数据.csv', encoding='gbk')
df

      year   country           GDP
0     1960        美国  543300000000
1     1960        英国   73233967692
2     1960        法国   62225478000
3     1960        中国   59716467625
4     1960        日本   44307342950
...    ...       ...           ...
9925  2019  圣多美和普林西比     418637388
9926  2019        帕劳     268354919
9927  2019      基里巴斯     194647201
9928  2019        瑙鲁     118223430
9929  2019       图瓦卢      47271463

[9930 rows x 3 columns]

In [3]:
# 2. 从原始数据集中 拷贝一部分出来 做操作. 
df2 = df[:5].copy()
df2

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [4]:
# 3. 新增列. 
# 思路1: 通过直接 赋值 的方式 新增1列.    column, 列
df2['c1'] = 23              # 写法1: 固定值 
df2['c2'] = ['cxk', 'lyf', 'wyf', 'wyb', '水冷哥'] # 写法2: 传入列表
df2['c3'] = df2.year * 2    # 写法3: 通过已有的列(Series) 来计算新列的值.

def my_fun1():
    return 25000

df2['c4'] = my_fun1()       # 写法4: 通过函数来计算新列的值.

# 4. 打印结果
df2

   year country           GDP  c1   c2    c3     c4
0  1960      美国  543300000000  23  cxk  3920  25000
1  1960      英国   73233967692  23  lyf  3920  25000
2  1960      法国   62225478000  23  wyf  3920  25000
3  1960      中国   59716467625  23  wyb  3920  25000
4  1960      日本   44307342950  23  水冷哥  3920  25000

In [5]:
# 思路2: 通过 assign() 的方式 新增1列.
df3 = df[:5].copy()
df3

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [6]:
# 写法1: 通过 assign()函数 -> 新增1列.
df3.assign(c1 = 23)

   year country           GDP  c1
0  1960      美国  543300000000  23
1  1960      英国   73233967692  23
2  1960      法国   62225478000  23
3  1960      中国   59716467625  23
4  1960      日本   44307342950  23

In [7]:
# 写法2: 通过 assign()函数 -> 新增n列.
df3.assign(
    c1 = 23,
    c2 = ['cxk', 'lyf', 'wyf', 'wyb', '水冷哥'],
    c3 = df3.year * 2,
    c4 = my_fun1()
)

   year country           GDP  c1   c2    c3     c4
0  1960      美国  543300000000  23  cxk  3920  25000
1  1960      英国   73233967692  23  lyf  3920  25000
2  1960      法国   62225478000  23  wyf  3920  25000
3  1960      中国   59716467625  23  wyb  3920  25000
4  1960      日本   44307342950  23  水冷哥  3920  25000

# 2.Pandas的增删改查操作 -> 删和去重

In [8]:
# 1. 准备数据.
df4 = df[:10].copy()
df4

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
5  1960     加拿大   40461721692
6  1960     意大利   40385288344
7  1960      印度   37029883875
8  1960    澳大利亚   18577668271
9  1960      瑞典   15822585033

In [9]:
# 2. 删除行 -> drop()函数, 除非指定inplace=True, 否则不会修改原始数据.
# df4.drop(index=[0, 2, 4])         # 不会修改原始数据.
df4.drop(index=[0], inplace=True)   # 会修改原始数据.

In [10]:
# 3. 删除列 -> del关键字, 会直接修改元数据.
del df4['year']     # 删除year列.
df4

  country          GDP
1      英国  73233967692
2      法国  62225478000
3      中国  59716467625
4      日本  44307342950
5     加拿大  40461721692
6     意大利  40385288344
7      印度  37029883875
8    澳大利亚  18577668271
9      瑞典  15822585033

In [ ]:
# 4. 删除列 -> drop()函数
# df4.drop(columns=['country'], inplace=True)
df4

In [11]:
# 5. 去重. 
# 场景1: DataFrame去重 -> 以 行 做单位比较.
df5 = df[:5].copy()

# 拼接df5 和 df5 -> 组合成 有重复数据的 DataFrame.
df6 = pd.concat([df5, df5])
df6

# DataFrame去重
df6.drop_duplicates()   # 如果设置inplace=True, 则会修改原始数据.

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [12]:
# 场景2: Series去重 -> 以 列 做单位比较.
df6.country.drop_duplicates()
df.country.drop_duplicates()

0          美国
1          英国
2          法国
3          中国
4          日本
        ...
6462    美属萨摩亚
7492       瑙鲁
7604      南苏丹
8269      库拉索
8292    荷属圣马丁
Name: country, Length: 210, dtype: str

# 3. Pandas的增删改查操作 -> 改

In [13]:
# 1. 准备源数据.
df7 = df[:5].copy()
df7

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [14]:
# 2. 新增1列
df7['c1'] = 23
df7

   year country           GDP  c1
0  1960      美国  543300000000  23
1  1960      英国   73233967692  23
2  1960      法国   62225478000  23
3  1960      中国   59716467625  23
4  1960      日本   44307342950  23

In [15]:
# 3. 修改GDP列值.
df7['GDP'] = [1, 2, 1, 66666666, -123]  # 直接修改原数据了.
df7

   year country       GDP  c1
0  1960      美国         1  23
1  1960      英国         2  23
2  1960      法国         1  23
3  1960      中国  66666666  23
4  1960      日本      -123  23

In [23]:
# 4. 采用 replace()替换.
# 美国 -> usa
df7['country'] = df7['country'].replace('美国', 'usa')  # 会修改原

# 日本 -> 岛国
df7['country'] = df7['country'].replace('日本', '岛国')
df7

   year country       GDP  c1
0  1960     usa         1  23
1  1960      英国         2  23
2  1960      法国         1  23
3  1960      中国  66666666  23
4  1960      岛国      -123  23

# 4. Pandas的增删改查操作 -> 查 和 排序

In [24]:
# 1. 查看源数据
df

      year   country           GDP
0     1960        美国  543300000000
1     1960        英国   73233967692
2     1960        法国   62225478000
3     1960        中国   59716467625
4     1960        日本   44307342950
...    ...       ...           ...
9925  2019  圣多美和普林西比     418637388
9926  2019        帕劳     268354919
9927  2019      基里巴斯     194647201
9928  2019        瑙鲁     118223430
9929  2019       图瓦卢      47271463

[9930 rows x 3 columns]

In [25]:
# 2. 获取前5条数据.
df.head(5)
df.head()   # 效果同上, 默认是5条

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [26]:
# 3. 获取后3条数据.
df.tail(3)

      year country        GDP
9927  2019    基里巴斯  194647201
9928  2019      瑙鲁  118223430
9929  2019     图瓦卢   47271463

In [27]:
# 4. 根据列名获取数据.
df['year']          # 获取year列 -> Series对象
df.year             # 获取year列 -> Series对象, 效果同上.

df[['year']]        # 获取year列 -> DataFrame对象

df[['year', 'country']]     # 获取year和country列 -> DataFrame对象

      year   country
0     1960        美国
1     1960        英国
2     1960        法国
3     1960        中国
4     1960        日本
...    ...       ...
9925  2019  圣多美和普林西比
9926  2019        帕劳
9927  2019      基里巴斯
9928  2019        瑙鲁
9929  2019       图瓦卢

[9930 rows x 2 columns]

In [28]:
# 5. 根据 行索引值来获取数据.
df[:5]      # 前5条
df[1:5:2]   # 1, 3, 包左不包右.
df[10::5]   # 从10开始, 到末尾结束, 步长为 5

      year   country          GDP
10    1960        巴西  15165569912
15    1960       比利时  11658722590
20    1960       奥地利   6592693841
25    1960        希腊   4335186016
30    1960      哥伦比亚   4031152976
...    ...       ...          ...
9905  2019       莱索托   2376328637
9910  2019       伯利兹   1879613600
9915  2019     几内亚比绍   1339449165
9920  2019      瓦努阿图    934239973
9925  2019  圣多美和普林西比    418637388

[1984 rows x 3 columns]

In [29]:
# 6. 通过query()函数, 结合条件获取.
# 需求: 查询中美日三国 2015 ~ 2019年的数据.
df.query('country in ["中国", "美国", "日本"] and year in [2015, 2016, 2017, 2018, 2019]')
df.query('country in ["中国", "美国", "日本"] and (year >= 2015 and year <= 2019)')

      year country             GDP
8928  2015      美国  18224700000000
8929  2015      中国  11061600000000
8930  2015      日本   4389480000000
9133  2016      美国  18715000000000
9134  2016      中国  11233300000000
9135  2016      日本   4922540000000
9338  2017      美国  19519400000000
9339  2017      中国  12310400000000
9340  2017      日本   4866860000000
9542  2018      美国  20580200000000
9543  2018      中国  13894800000000
9544  2018      日本   4954810000000
9745  2019      美国  21433200000000
9746  2019      中国  14279900000000
9747  2019      日本   5081770000000

In [30]:
# 7. 排序.
df.sort_index(ascending=False)      # 根据 行索引值排序, 降序.

      year   country           GDP
9929  2019       图瓦卢      47271463
9928  2019        瑙鲁     118223430
9927  2019      基里巴斯     194647201
9926  2019        帕劳     268354919
9925  2019  圣多美和普林西比     418637388
...    ...       ...           ...
4     1960        日本   44307342950
3     1960        中国   59716467625
2     1960        法国   62225478000
1     1960        英国   73233967692
0     1960        美国  543300000000

[9930 rows x 3 columns]

In [31]:
# 根据内容, 例如: year 降序, 一致就根据 GDP降序.
df.sort_values(['year', 'GDP'], ascending=False)
df.sort_values(['year', 'GDP'], ascending=[False, True])    # year 降序, GDP升序.

      year   country           GDP
9929  2019       图瓦卢      47271463
9928  2019        瑙鲁     118223430
9927  2019      基里巴斯     194647201
9926  2019        帕劳     268354919
9925  2019  圣多美和普林西比     418637388
...    ...       ...           ...
4     1960        日本   44307342950
3     1960        中国   59716467625
2     1960        法国   62225478000
1     1960        英国   73233967692
0     1960        美国  543300000000

[9930 rows x 3 columns]

In [32]:
# 8. rank()函数, 类似于SQL的窗口函数. 
df7 = pd.DataFrame({
    '姓名':['小明', '小美', '小强', '小兰'],
    '成绩':[100, 90, 90, 80]
})
df7

   姓名   成绩
0  小明  100
1  小美   90
2  小强   90
3  小兰   80

In [33]:
# 9. rank()直接排名
# df7.rank()      # 针对于每列都会排名

# 给df新增1列, 用于显示排名.
df7['成绩排名_min'] = df7.成绩.rank(method='min', ascending=False)
df7['成绩排名_max'] = df7.成绩.rank(method='max', ascending=False)
df7['成绩排名_dense'] = df7.成绩.rank(method='dense', ascending=False)
df7['成绩排名_avg'] = df7.成绩.rank(method='average', ascending=False)
df7['成绩排名_默认'] = df7.成绩.rank(ascending=False)

df7

   姓名   成绩  成绩排名_min  成绩排名_max  成绩排名_dense  成绩排名_avg  成绩排名_默认
0  小明  100       1.0       1.0         1.0       1.0      1.0
1  小美   90       2.0       3.0         2.0       2.5      2.5
2  小强   90       2.0       3.0         2.0       2.5      2.5
3  小兰   80       4.0       4.0         3.0       4.0      4.0