In [1]:
import pandas as pd
import numpy as np
import os
os.chdir(r'C:/my_code/learning-notes/2.数据分析')   # 修改相对路径的位置.
# os.getcwd()

# 解决中文显示问题，下面的代码只需运行一次即可
import matplotlib as plt
plt.rcParams['font.sans-serif'] = ['SimHei']    # 如果是Mac本, 不支持SimHei的时候, 可以修改为 'Microsoft YaHei' 或者 'Arial Unicode MS'
plt.rcParams['axes.unicode_minus'] = False

# 1. Pandas进阶语法_缺失值处理

## 1.1 思路1: 删除缺失值

In [2]:
# 1. 读取数据.
movie_df = pd.read_csv('./data/movie.csv')
movie_df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [ ]:
# 2. 查看下数据的介绍.
movie_df.columns        # 所有的列名
movie_df.info()         # 查看数据的 基本信息(列名, 数据类型, 非缺失值数量等)
movie_df.describe()     # 查看数据的 描述性统计信息(均值, 中位数, 标准差等)

In [ ]:
# 3. 删除缺失值
# movie_df.dropna()   # 不会修改原数据, 加入 inplace=True 即可, 默认删: axis=0, 删行, axis=1, 删列.

# movie_df.dropna(axis=0)     # 删行
movie_df.dropna(axis=1)      # 删列

## 1.2 思路2: 填充缺失值

In [3]:
# 1. 查看源数据
movie_df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [4]:
# 2. 判断某列(的某个值)是否有缺失值. 
pd.isnull(movie_df)     # 判断df对象的 每列的 每个值 是否为空(缺失值)
pd.notnull(movie_df)    # 判断df对象的 每列的 每个值 是否不为空(非缺失值)

# 3.判断某列是否是 包含缺失值的列. 
np.all(pd.notnull(movie_df))    # 整列都是True -> 结果是True, 但凡有False -> 结果是False, 说明该列有缺失.

np.False_

In [ ]:
# 4. 填充缺失值.
# 写法1: 填充固定值.
movie_df.fillna(23).info()

In [5]:
# 写法2: 填充 每列的平均值.
movie_df['Revenue (Millions)'] = movie_df['Revenue (Millions)'].fillna(movie_df['Revenue (Millions)'].mean())
movie_df['Metascore'] = movie_df['Metascore'].fillna(movie_df['Metascore'].mean())
movie_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   str
 2   Genre               1000 non-null   str
 3   Description         1000 non-null   str
 4   Director            1000 non-null   str
 5   Actors              1000 non-null   str
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
dtypes: float64(3), int64(4), str(5)
memory usage: 93.9 KB

In [6]:
# 5. for循环的方式, 使用 每列的平均值 来填充各列的缺失值. 
# 5.1 获取每个列名
for col_name in movie_df.columns:
    # 5.2 判断某列是否有缺失值.
    # movie_df[col_name]:  根据列名, 找到 df中的某个列 -> Series对象.
    # pd.notnull(某列数据): 判断该列的每个值是否为非缺失值, True -> 不为空, False -> 为空(缺失值)
    # np.all([True, False...]): 里边的值全部为True -> 结果为True, 只要有一个为False -> 结果为False.
    if np.all(pd.notnull(movie_df[col_name])) == False:
        # 5.3 走到这里, 说明该列有缺失值.
        print(col_name)     # 打印列名
        # 5.4 打印这两列的平均值. 
        print(movie_df[col_name].mean())
        # 5.5 用该列的平均值来填充该列的缺失值.
        movie_df[col_name].fillna(movie_df[col_name].mean(), inplace=True)

In [7]:
# 6. 查看处理后的结果.
movie_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   str
 2   Genre               1000 non-null   str
 3   Description         1000 non-null   str
 4   Director            1000 non-null   str
 5   Actors              1000 non-null   str
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
dtypes: float64(3), int64(4), str(5)
memory usage: 93.9 KB

## 1.3 思路3: 转换, 然后填充或者删除缺失值

In [8]:
# 背景: 实际开发中, 不是所有的缺失值都会用NaN来表示, 例如: 可能用 ? 表示, 如何删除这些缺失值呢? 
# 思路: 先转换, 后删除.  即:  ? -> NaN -> 删除.
# 1. 加载数据.
wis = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data")
wis

     1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[698 rows x 11 columns]

In [9]:
# 2. 尝试直接删除缺失值.
wis.dropna()        # ? 不是缺失值, 所以直接删, 删不掉.

     1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[698 rows x 11 columns]

In [10]:
# 3. 解决上述的问题, ? -> NaN -> 删.            空的三种写法: np.nan, np.NAN, np.NaN
wis.replace('?', np.nan).dropna()

     1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[682 rows x 11 columns]

# 2. 数据合并

## 2.1 思路1: concat(), 能行合并, 还是列合并

In [11]:
# 1. 准备数据. 
df = pd.read_csv('./data/1960-2019全球GDP数据.csv', encoding='gbk')
df

df1 = df[:10]
df1

df2 = df[10:20]
df2

    year country          GDP
10  1960      巴西  15165569912
11  1960     土耳其  13995067817
12  1960     墨西哥  13040000000
13  1960      荷兰  12276734172
14  1960     西班牙  12072126075
15  1960     比利时  11658722590
16  1960      瑞士   9522746719
17  1960    委内瑞拉   7779090909
18  1960      南非   7575396972
19  1960     菲律宾   6684568805

In [15]:
# 2. 通过 concat() 合并数据.
# 细节: 列合并默认参考 列名.  
new_df = pd.concat([df1, df2], axis=0)  # axis=0, 列合并(垂直合并), axis=1, 行合并(水平合并)
new_df = pd.concat([df1, df2])          # 效果同上, 默认是 列合并

# 细节: 行合并, 默认参考 行索引(值)
new_df = pd.concat([df1, df2], axis=1)  # 行合并
new_df

      year country           GDP    year country           GDP
0   1960.0      美国  5.433000e+11     NaN     NaN           NaN
1   1960.0      英国  7.323397e+10     NaN     NaN           NaN
2   1960.0      法国  6.222548e+10     NaN     NaN           NaN
3   1960.0      中国  5.971647e+10     NaN     NaN           NaN
4   1960.0      日本  4.430734e+10     NaN     NaN           NaN
5   1960.0     加拿大  4.046172e+10     NaN     NaN           NaN
6   1960.0     意大利  4.038529e+10     NaN     NaN           NaN
7   1960.0      印度  3.702988e+10     NaN     NaN           NaN
8   1960.0    澳大利亚  1.857767e+10     NaN     NaN           NaN
9   1960.0      瑞典  1.582259e+10     NaN     NaN           NaN
10     NaN     NaN           NaN  1960.0      巴西  1.516557e+10
11     NaN     NaN           NaN  1960.0     土耳其  1.399507e+10
12     NaN     NaN           NaN  1960.0     墨西哥  1.304000e+10
13     NaN     NaN           NaN  1960.0      荷兰  1.227673e+10
14     NaN     NaN           NaN  1960.0     西班牙  1.207213e+10
15     NaN     NaN           NaN  1960.0     比利时  1.165872e+10
16     NaN     NaN           NaN  1960.0      瑞士  9.522747e+09
17     NaN     NaN           NaN  1960.0    委内瑞拉  7.779091e+09
18     NaN     NaN           NaN  1960.0      南非  7.575397e+09
19     NaN     NaN           NaN  1960.0     菲律宾  6.684569e+09

In [16]:
# 3. 修改df2的列索引.
df2.index = [0, 1, 2, 3, 4, 11, 12, 13, 14, 15]
df2

    year country          GDP
0   1960      巴西  15165569912
1   1960     土耳其  13995067817
2   1960     墨西哥  13040000000
3   1960      荷兰  12276734172
4   1960     西班牙  12072126075
11  1960     比利时  11658722590
12  1960      瑞士   9522746719
13  1960    委内瑞拉   7779090909
14  1960      南非   7575396972
15  1960     菲律宾   6684568805

In [17]:
# 4. 再次进行 行合并(参考: 行索引值)
pd.concat([df1, df2], axis=1)

      year country           GDP    year country           GDP
0   1960.0      美国  5.433000e+11  1960.0      巴西  1.516557e+10
1   1960.0      英国  7.323397e+10  1960.0     土耳其  1.399507e+10
2   1960.0      法国  6.222548e+10  1960.0     墨西哥  1.304000e+10
3   1960.0      中国  5.971647e+10  1960.0      荷兰  1.227673e+10
4   1960.0      日本  4.430734e+10  1960.0     西班牙  1.207213e+10
5   1960.0     加拿大  4.046172e+10     NaN     NaN           NaN
6   1960.0     意大利  4.038529e+10     NaN     NaN           NaN
7   1960.0      印度  3.702988e+10     NaN     NaN           NaN
8   1960.0    澳大利亚  1.857767e+10     NaN     NaN           NaN
9   1960.0      瑞典  1.582259e+10     NaN     NaN           NaN
11     NaN     NaN           NaN  1960.0     比利时  1.165872e+10
12     NaN     NaN           NaN  1960.0      瑞士  9.522747e+09
13     NaN     NaN           NaN  1960.0    委内瑞拉  7.779091e+09
14     NaN     NaN           NaN  1960.0      南非  7.575397e+09
15     NaN     NaN           NaN  1960.0     菲律宾  6.684569e+09

In [20]:
# 5. 再次进行行合并. 
# 默认是: 满外连接, 即: 左表全集 + 右表全集 + 交集
pd.concat([df1, df2], axis=1, join='outer')    

# 指定为: 内连接, 即: 只要交集
pd.concat([df1, df2], axis=1, join='inner')

   year country           GDP  year country          GDP
0  1960      美国  543300000000  1960      巴西  15165569912
1  1960      英国   73233967692  1960     土耳其  13995067817
2  1960      法国   62225478000  1960     墨西哥  13040000000
3  1960      中国   59716467625  1960      荷兰  12276734172
4  1960      日本   44307342950  1960     西班牙  12072126075

## 2.2 思路2: merge() -> 只能进行 行合并(水平合并)

In [22]:
# 1. 准备数据集.
df1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                        'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                        'key2': ['K0', 'K0', 'K0', 'K0'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})

# 2. 查看数据
df1
df2

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [23]:
# 3. 演示 merge()函数的 默认合并方式.
pd.merge(df1, df2, how='inner', on=['key1', 'key2'])
pd.merge(df1, df2)      # 效果同上, 默认是 inner join, 且参考 同名列进行合并.

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [24]:
# 4. 内连接, 指定合并字段
pd.merge(df1, df2, how='inner', on='key2')  # 内连接, 关联字段为: key2

  key1_x key2   A   B key1_y   C   D
0     K0   K0  A0  B0     K0  C0  D0
1     K0   K0  A0  B0     K1  C1  D1
2     K0   K0  A0  B0     K1  C2  D2
3     K0   K0  A0  B0     K2  C3  D3
4     K1   K0  A2  B2     K0  C0  D0
5     K1   K0  A2  B2     K1  C1  D1
6     K1   K0  A2  B2     K1  C2  D2
7     K1   K0  A2  B2     K2  C3  D3

In [25]:
# 5. 外连接, 指定合并字段.
pd.merge(df1, df2, how='outer', on=['key1', 'key2'])    # 满外连接, 关联字段为: key1, key2

# 左外连接 = 左表全集 + 交集
# pd.merge(df1, df2, how='left', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [26]:
# 6. merge()函数的其它写法.
df1.merge(df2, how='inner', on='key1')      # 效果同上, 即: df1.merge(df2)

# 回顾: concat写法(),   pd.concat([df1, df2...])        可以同时拼接多个, 既能行合并, 也能列合并, 不能指定合并字段. 默认是: 外连接合并方式.
# df1.concat(df2)     # 错误写法.
pd.concat([df1, df2, df1])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0  NaN  NaN
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2  NaN  NaN
3   K2   K1   A3   B3  NaN  NaN
0   K0   K0  NaN  NaN   C0   D0
1   K1   K0  NaN  NaN   C1   D1
2   K1   K0  NaN  NaN   C2   D2
3   K2   K0  NaN  NaN   C3   D3
0   K0   K0   A0   B0  NaN  NaN
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2  NaN  NaN
3   K2   K1   A3   B3  NaN  NaN

# 3. groupby() 分组聚合 以及 分组过滤

In [27]:
# 1. 读取数据
df = pd.read_csv('./data/uniqlo.csv')
df

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,658,深圳,线下,Female,25-29,Weekday,当季新品,4,796.0,4,4,59
1,146,杭州,线下,Female,25-29,Weekday,运动,1,149.0,1,1,49
2,70,深圳,线下,Male,>=60,Weekday,T恤,2,178.0,2,2,49
3,658,深圳,线下,Female,25-29,Weekday,T恤,1,59.0,1,1,49
4,229,深圳,线下,Male,20-24,Weekend,袜子,2,65.0,2,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...
22288,146,杭州,线下,Female,30-34,Weekday,短裤,1,80.0,1,2,19
22289,430,成都,线下,Female,25-29,Weekend,T恤,1,79.0,1,1,49
22290,449,武汉,线下,Female,35-39,Weekday,T恤,1,158.0,1,2,49
22291,758,杭州,线下,Female,20-24,Weekday,袜子,1,26.0,1,1,9
22292,616,成都,线下,Male,30-34,Weekday,当季新品,1,79.0,1,1,59

## 3.1 分组聚合

In [28]:
# agg -> Aggregate(聚合的意思)
# 格式: df.groupby(['分组字段1', '分组字段2'...]).agg({'列名1':'聚合函数名', '列名2':'聚合函数名'...})

In [29]:
# 1. 场景1: 按照单列分组
df.groupby(['city'])        # DataFrameGroupBy  -> DataFrame分组对象
df.groupby('city')        # 细节: 如果分组列只有1个, 中括号可以省略不写.

In [30]:
# 2. 场景2: 按照多列分组
df.groupby(['city', 'channel'])             # DataFrameGroupBy  -> DataFrame分组对象
df.groupby(['city', 'channel']).revenue     # SeriesGroupBy  -> Series分组对象

In [31]:
# 3. 场景3: 如何获取某个分组的数据. 
df.groupby(['city', 'channel']).get_group(('北京', '线下'))     # 1个分组的信息
df.groupby(['city', 'channel']).get_group(('上海', '线上'))     # 另1个分组的信息

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
49,207,上海,线上,Female,20-24,Weekend,T恤,1,99.00,1,1,49
144,207,上海,线上,Female,35-39,Weekday,牛仔裤,1,39.00,1,1,69
187,207,上海,线上,Male,30-34,Weekday,T恤,1,99.00,1,1,49
189,207,上海,线上,Female,50-54,Weekday,配件,1,115.62,1,2,29
253,207,上海,线上,Female,20-24,Weekday,T恤,1,79.00,1,1,49
...,...,...,...,...,...,...,...,...,...,...,...,...
22051,207,上海,线上,Female,25-29,Weekend,袜子,1,38.00,1,1,9
22145,207,上海,线上,Male,25-29,Weekday,T恤,3,195.00,3,3,49
22211,207,上海,线上,Female,35-39,Weekend,牛仔裤,1,79.00,1,1,69
22215,207,上海,线上,Female,30-34,Weekday,T恤,9,411.00,9,9,49
22243,207,上海,线上,Female,20-24,Weekday,当季新品,1,55.32,1,1,59

In [32]:
# 4. 场景4: 分组 + 聚合(聚合字段只有1个)
# 需求: 根据 城市 和 销售渠道分组, 计算: 销售金额.
# 写法1: 通用版(掌握)
df.groupby(['city', 'channel']).agg({'revenue':'sum'})      # 返回DataFrame对象

# 写法2: 变形版(了解)
df.groupby(['city', 'channel']).revenue.sum()               # 返回Series对象
df.groupby(['city', 'channel'])['revenue'].sum()            # 返回Series对象
df.groupby(['city', 'channel'])[['revenue']].sum()          # 返回DataFrame对象

                revenue
city channel
上海   线上       114438.09
     线下       275383.64
北京   线下       130458.62
南京   线下       123150.93
广州   线上       200893.30
     线下       117231.19
成都   线下       208189.86
杭州   线下       589518.49
武汉   线上       281420.73
     线下       308357.05
深圳   线下       733123.68
西安   线上        30088.01
     线下       180686.61
重庆   线上        26330.35
     线下       237162.30

In [33]:
# 5. 场景5: 分组 + 聚合(聚合字段有2个, 聚合操作相同)
# 需求: 根据 城市 和 销售渠道分组, 计算: 销售金额, 订单数量 总和.
# 写法1: 通用版(掌握)
df.groupby(['city', 'channel']).agg({'revenue':'sum', 'order':'sum'})

# 写法2: 变形版(了解)
df.groupby(['city', 'channel'])[['revenue', 'order']].sum()

                revenue  order
city channel
上海   线上       114438.09   1237
     线下       275383.64   2800
北京   线下       130458.62   1303
南京   线下       123150.93   1113
广州   线上       200893.30   2115
     线下       117231.19   1277
成都   线下       208189.86   2263
杭州   线下       589518.49   6196
武汉   线上       281420.73   2895
     线下       308357.05   3101
深圳   线下       733123.68   7475
西安   线上        30088.01    325
     线下       180686.61   1954
重庆   线上        26330.35    251
     线下       237162.30   2523

In [34]:
# 6. 场景6: 分组 + 聚合(聚合字段有2个, 聚合操作不同)
# 需求: 根据 城市 和 销售渠道分组, 分别计算: 销售金额的平均值, 成本的总和.
df.groupby(['city', 'channel']).agg({
    'revenue': 'mean',
    'unit_cost': 'sum'
})

                 revenue  unit_cost
city channel
上海   线上       187.603426      27980
     线下       154.623043      82359
北京   线下       226.098128      26163
南京   线下       246.301860      23140
广州   线上       153.470817      59631
     线下       133.368817      41091
成都   线下       136.160798      72041
杭州   线下       155.751252     173445
武汉   线上       180.977961      69225
     线下       153.258971      93858
深圳   线下       167.993511     201526
西安   线上       128.581239      10246
     线下       131.791838      64469
重庆   线上       144.672253       8028
     线下       147.764673      75055

## 3.2 分组过滤

In [ ]:
# 需求: 按照城市分组, 查询每组销售金额平均值 大于200的全部数据.    即: 算出每组的销售金额, 找到金额大于200的组, 然后显示这些组所有的信息.

# 1.根据城市分组, 计算每个城市的 销售金额的 平均值
df.groupby('city').revenue.mean()       

# 2. 根据城市分组, 查看上海分组的数据.
df.groupby('city').get_group('上海')

# 3. 完成需求.
df.groupby('city').filter(lambda x: x.revenue.mean() > 200)
df.groupby('city').revenue.filter(lambda x: x.mean() > 200)

# 4. 上边的代码等价于 找到  city值为 北京, 南京的数据. 
df.query('city in ["北京", "南京"]')

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.0,1,1,99
23,19,南京,线下,Female,35-39,Weekend,T恤,4,176.0,4,4,49
40,19,南京,线下,Female,45-49,Weekday,毛衣,2,198.0,2,2,99
62,19,南京,线下,Female,35-39,Weekend,T恤,2,197.0,2,2,49
168,21,北京,线下,Female,35-39,Weekday,毛衣,3,447.0,3,3,99
...,...,...,...,...,...,...,...,...,...,...,...,...
22182,19,南京,线下,Female,30-34,Weekend,当季新品,1,79.0,1,1,59
22192,21,北京,线下,Female,20-24,Weekday,T恤,7,693.0,7,7,49
22251,19,南京,线下,Female,45-49,Weekend,短裤,1,39.0,1,1,19
22273,21,北京,线下,Female,20-24,Weekday,当季新品,2,288.0,2,2,59
22280,21,北京,线下,Female,35-39,Weekend,T恤,1,59.0,1,1,49

# 4. 交叉表(了解) 和 透视表(掌握)

In [45]:
# 1. 交叉表演示: 
# 创建一个示例数据集
data = {
    '性别': ['男', '女', '男', '女', '男', '女', '女', '男'],
    '购买': ['是', '否', '是', '是', '否', '否', '是', '否']
}

df = pd.DataFrame(data)

# 创建交叉表
crosstab = pd.crosstab(df['性别'], df['购买'])
print(crosstab)

购买  否  是
性别
女   2  2
男   2  2

In [46]:
# 2. 用透视表完成上述的需求.
data = {
    '性别': ['男', '女', '男', '女', '男', '女'],
    '购买': ['是', '否', '是', '是', '否', '否'],
    '金额': [100, 150, 200, 130, 160, 120]
}
df = pd.DataFrame(data)
df.pivot_table(index='性别', columns='购买', values='金额' , aggfunc='mean')

购买      否      是
性别
女   135.0  130.0
男   160.0  150.0

In [47]:
# 3. 透视表案例: 优衣库数据集.
# 3.1 读取数据
df = pd.read_csv('./data/uniqlo.csv')
df

# 3.2 需求: 根据城市, 销售渠道分组, 计算 销售金额 总和.
# 写法1: groupby() 分组 聚合 
df.groupby(['city', 'channel']).agg({'revenue': 'sum'})
# df.groupby(['city', 'channel'], as_index=False).agg({'revenue': 'sum'})     # as_index=False 不把分组字段当做行索引, 而是当做列.

# 写法2: pivot_table() 透视表, 作用: 统计分组数据, 简化 分组聚合写法, 指定某一列对另一列的关系
# 参1: 指定分组字段, 参2: 指定分组字段, 参3: 指定聚合字段, 参4: 指定聚合函数
df.pivot_table(index='city', columns='channel', values='revenue', aggfunc='sum')

channel         线上         线下
city
上海       114438.09  275383.64
北京             NaN  130458.62
南京             NaN  123150.93
广州       200893.30  117231.19
成都             NaN  208189.86
杭州             NaN  589518.49
武汉       281420.73  308357.05
深圳             NaN  733123.68
西安        30088.01  180686.61
重庆        26330.35  237162.30